/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorRepuestos;
import Modelo.Repuestos;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JHONNY
 */
public class FRRepuestos extends javax.swing.JInternalFrame {

    ControladorRepuestos controlar = new ControladorRepuestos();
    
    public FRRepuestos() {
        initComponents();
        txtidRepuestos.setValue(0);
        txtidRepuestos.setVisible(false);
        limpiarFORMULARIO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        lblcantidad = new javax.swing.JLabel();
        lblbuscar = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtidRepuestos = new javax.swing.JFormattedTextField();
        lblprecio = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrepuestos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btinsertar = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btbuscar = new javax.swing.JButton();
        btcerrar = new javax.swing.JButton();

        textField1.setText("textField1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Repuestos");

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        lblnombre.setText("Nombre");

        lbltipo.setText("Tipo");

        lblcantidad.setText("Cantidad ");

        lblbuscar.setText("Buscar");

        txtnombre.setText("Escriba nombre");
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombreFocusGained(evt);
            }
        });

        txttipo.setText("Original o Generico");
        txttipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttipoFocusGained(evt);
            }
        });

        txtbuscar.setText("Escriba texto a buscar ");
        txtbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbuscarFocusLost(evt);
            }
        });

        txtcantidad.setText("Escriba la cantidad");
        txtcantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcantidadFocusGained(evt);
            }
        });

        txtidRepuestos.setText("0");
        txtidRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidRepuestosActionPerformed(evt);
            }
        });

        lblprecio.setText("Precio");

        txtprecio.setText("Escriba el precio");
        txtprecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtprecioFocusGained(evt);
            }
        });
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblnombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtidRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblprecio)
                            .addGap(18, 18, 18)
                            .addComponent(txtprecio))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblcantidad)
                            .addGap(18, 18, 18)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbltipo)
                        .addGap(18, 18, 18)
                        .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(lbltipo)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcantidad)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblprecio)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbuscar)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        tblrepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idRepuestos", "Nombre", "Cantidad", "tipo", "Precio "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblrepuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrepuestosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblrepuestos);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        btinsertar.setText("INSERTAR");
        btinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertarActionPerformed(evt);
            }
        });

        btmodificar.setText("MODIFICAR");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });

        bteliminar.setText("ELIMINAR");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btbuscar.setText("BUSCAR");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        btcerrar.setText("CERRAR");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btinsertar)
                .addGap(26, 26, 26)
                .addComponent(btmodificar)
                .addGap(29, 29, 29)
                .addComponent(bteliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btbuscar)
                .addGap(32, 32, 32)
                .addComponent(btcerrar)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btinsertar)
                    .addComponent(btmodificar)
                    .addComponent(bteliminar)
                    .addComponent(btbuscar)
                    .addComponent(btcerrar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidRepuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidRepuestosActionPerformed

    private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarActionPerformed
 
    doDefaultCloseAction();
// TODO add your handling code here:
    }//GEN-LAST:event_btcerrarActionPerformed

    private void btinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertarActionPerformed
        controlar.controlarAccion(evt, obtenerunrep());
        limpiarFORMULARIO();
        // TODO add your handling code here:
    }//GEN-LAST:event_btinsertarActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        controlar.controlarAccion(evt, obtenerunrep());
        limpiarFORMULARIO();
        // TODO add your handling code here:
    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        controlar.controlarAccion(evt, obtenerunrep());
        limpiarFORMULARIO();
        // TODO add your handling code here:
    }//GEN-LAST:event_bteliminarActionPerformed

    private void tblrepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrepuestosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int fila = tblrepuestos.rowAtPoint(evt.getPoint());
            if (fila > -1) {
                txtidRepuestos.setValue(tblrepuestos.getValueAt(fila, 0)); // Suponiendo que txtidRepuestos es un campo de tipo Integer
                txtnombre.setText((String) tblrepuestos.getValueAt(fila, 1));
                int cantidad = (int) tblrepuestos.getValueAt(fila, 2); // Obtener como entero
                txtcantidad.setText(String.valueOf(cantidad)); // Convertir a String antes de asignarlo al campo de texto
                txttipo.setText((String) tblrepuestos.getValueAt(fila, 3));
                int precio = (int) tblrepuestos.getValueAt(fila, 4); // Obtener como entero
                txtprecio.setText(String.valueOf(precio)); // Convertir a String antes de asignarlo al campo de texto
                btmodificar.setEnabled(true);
                bteliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblrepuestosMouseClicked

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        // TODO add your handling code here:
        llenarTablaConBuscar(txtbuscar.getText());
    }//GEN-LAST:event_btbuscarActionPerformed

    private void txtbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusGained
        txtbuscar.setText("");
        if(txtbuscar.getText().equals("Escriba texto a buscar")){
            txtbuscar.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarFocusGained

    private void txtbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusLost
        // TODO add your handling code here:
        if ( txtbuscar.getText().isEmpty()){
            txtbuscar.setText("Escriba texto a buscar");
        }
    }//GEN-LAST:event_txtbuscarFocusLost

    private void txtcantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcantidadFocusGained
        // TODO add your handling code here:
        txtcantidad.setText("");
    }//GEN-LAST:event_txtcantidadFocusGained

    private void txtnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusGained
        // TODO add your handling code here:
        txtnombre.setText("");
    }//GEN-LAST:event_txtnombreFocusGained

    private void txttipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttipoFocusGained
        // TODO add your handling code here:
        txttipo.setText("");
    }//GEN-LAST:event_txttipoFocusGained

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtprecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtprecioFocusGained
        // TODO add your handling code here:
        txtprecio.setText("");
    }//GEN-LAST:event_txtprecioFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btcerrar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btinsertar;
    private javax.swing.JButton btmodificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JTable tblrepuestos;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JFormattedTextField txtidRepuestos;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables

    private void limpiarFORMULARIO() {
        txtidRepuestos.setValue(0);
        txtnombre.setText("escriba nombre");
        txtcantidad.setText("escriba cantidad");
        txttipo.setText("escriba el tipo");
        txtprecio.setText("escriba el precio");
        btmodificar.setEnabled(false);
        bteliminar.setEnabled(false);
        llenarTABLA();
    }

    private void llenarTABLA() {
        Repuestos unrepuesto = new Repuestos();
        DefaultTableModel tabla = (DefaultTableModel)tblrepuestos.getModel();
        Iterator<Repuestos> itrepuestos = unrepuesto.listar();
        Object[] filarepuestos = new Object[tblrepuestos.getColumnCount()];
        tabla.setRowCount(0);
        while (itrepuestos.hasNext()){
            unrepuesto = itrepuestos.next();
            filarepuestos[0] = unrepuesto.getIdRepuestos();
            filarepuestos[1] = unrepuesto.getNombre();
            filarepuestos[2] = unrepuesto.getCantidad();
            filarepuestos[3] = unrepuesto.getTipo();
            filarepuestos[4] = unrepuesto.getPrecio();
            tabla.addRow(filarepuestos);
        }
    }

    private Repuestos obtenerunrep() {
        Repuestos elrepuesto = new Repuestos();
        elrepuesto.setIdRepuestos((Integer) txtidRepuestos.getValue());
        elrepuesto.setNombre( txtnombre.getText());
        elrepuesto.setCantidad( Integer.parseInt(txtcantidad.getText()));
        elrepuesto.setTipo( txttipo.getText());
        elrepuesto.setPrecio( Integer.parseInt(txtprecio.getText()));
        return elrepuesto;
    }

    private void llenarTablaConBuscar(String busqueda) {
         Repuestos unrepuesto = new Repuestos();
        DefaultTableModel tabla = (DefaultTableModel)tblrepuestos.getModel();
        Iterator<Repuestos> itrepuestos = unrepuesto.buscar(busqueda);
        Object[] filarepuestos = new Object[tblrepuestos.getColumnCount()];
        tabla.setRowCount(0);
        while (itrepuestos.hasNext()){
            unrepuesto = itrepuestos.next();
            filarepuestos[0] = unrepuesto.getIdRepuestos();
            filarepuestos[1] = unrepuesto.getNombre();
            filarepuestos[2] = unrepuesto.getCantidad();
            filarepuestos[3] = unrepuesto.getTipo();
            filarepuestos[4] = unrepuesto.getPrecio();
            ((DefaultTableModel) tblrepuestos.getModel()).addRow(filarepuestos);
        }
    }
}
