/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import Modelo.ConexionBD;
import Modelo.Ventas;
import java.beans.PropertyVetoException;

/**
 *
 * @author JHONNY
 */
public class Gomotos extends javax.swing.JFrame {

    FRCliente   micli;
    FRProveedor mipro;
    FRVentas   miventa;
    FRRepuestos mirep;
    FRMFactura mifactura;
    /**
     * Creates new form Gomotos
     */
    public Gomotos() {
        ConexionBD.getInstance();
        initComponents();
        this.setLocationRelativeTo(null);
        micli = new FRCliente();
        mipro = new FRProveedor();
        miventa = new FRVentas();
        mirep = new FRRepuestos();
        mifactura = new FRMFactura();
        
        // agregamos los otros formularios
        gomotos.add(micli);
        gomotos.add(mipro);
        gomotos.add(miventa);
        gomotos.add(mirep);
        gomotos.add(mifactura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gomotos = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ClienteMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        ProveedorMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        RepuestosMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        newVentaMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        FacturaMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SalirMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gomotos.setBackground(new java.awt.Color(255, 255, 255));
        gomotos.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 30, 0, 1);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cliente");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        ClienteMenuItem1.setText("Cliente");
        ClienteMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(ClienteMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Proveedor");

        ProveedorMenuItem2.setText("Proveedor");
        ProveedorMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(ProveedorMenuItem2);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Repuestos");

        RepuestosMenuItem3.setText("Repuestos");
        RepuestosMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepuestosMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(RepuestosMenuItem3);

        menuBar.add(helpMenu);

        jMenu1.setText("Ventas");

        newVentaMenuItem4.setText("New Venta");
        newVentaMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVentaMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(newVentaMenuItem4);

        menuBar.add(jMenu1);

        jMenu3.setText("Factura");

        FacturaMenuItem1.setText("Factura");
        FacturaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(FacturaMenuItem1);

        menuBar.add(jMenu3);

        jMenu2.setText("Cerrar Sesion");

        SalirMenuItem5.setText("Salir");
        SalirMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(SalirMenuItem5);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gomotos, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gomotos, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fileMenuActionPerformed

    private void ClienteMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteMenuItem1ActionPerformed
        // TODO add your handling code here:
        micli.setVisible(true);
    }//GEN-LAST:event_ClienteMenuItem1ActionPerformed

    private void RepuestosMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepuestosMenuItem3ActionPerformed
        // TODO add your handling code here:
        mirep.setVisible(true);
    }//GEN-LAST:event_RepuestosMenuItem3ActionPerformed

    private void newVentaMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVentaMenuItem4ActionPerformed
        // TODO add your handling code here:
        miventa.setVisible(true);
    }//GEN-LAST:event_newVentaMenuItem4ActionPerformed

    private void SalirMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenuItem5ActionPerformed
        // TODO add your handling code here:
         ConexionBD.Desconectar();
        try{
            micli.setClosed(true);
            mipro.setClosed(true);
            miventa.setClosed(true);
            mirep.setClosed(true);
            mifactura.setClosed(true);
        }catch (PropertyVetoException ex){
            System.err.println("Error al salir:"+ex.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_SalirMenuItem5ActionPerformed

    private void ProveedorMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorMenuItem2ActionPerformed
        // TODO add your handling code here:
        mipro.setVisible(true);
    }//GEN-LAST:event_ProveedorMenuItem2ActionPerformed

    private void FacturaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaMenuItem1ActionPerformed
        // TODO add your handling code here:
        mifactura = new FRMFactura();
        gomotos.add(mifactura);
        mifactura.setVisible(true);
    }//GEN-LAST:event_FacturaMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gomotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gomotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gomotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gomotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gomotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteMenuItem1;
    private javax.swing.JMenuItem FacturaMenuItem1;
    private javax.swing.JMenuItem ProveedorMenuItem2;
    private javax.swing.JMenuItem RepuestosMenuItem3;
    private javax.swing.JMenuItem SalirMenuItem5;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JDesktopPane gomotos;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newVentaMenuItem4;
    // End of variables declaration//GEN-END:variables

}
